"""Additional government schemes catalog — merged with base seed data."""

from app.models.scheme import GovernmentLevel

ADDITIONAL_SCHEMES = [
    {
        "id": "SCH_PM_SVANIDHI",
        "name": "PM SVANidhi",
        "short_description": "Micro-credit up to ₹10,000 for street vendors to resume livelihoods.",
        "full_description": (
            "PM Street Vendor's AtmaNirbhar Nidhi provides affordable working capital loans "
            "up to ₹10,000 to street vendors, hawkers, and small traders with priority sector lending benefits."
        ),
        "government_level": GovernmentLevel.CENTRAL,
        "ministry": "Ministry of Housing & Urban Affairs",
        "category": "Micro Finance",
        "applicable_states": ["All India"],
        "benefits": ["Collateral-free loan up to ₹10,000", "Interest subsidy on timely repayment", "Digital payment incentives"],
        "required_documents": ["Aadhaar", "Vending certificate/ID", "Bank account"],
        "application_process": "Apply via PM SVANidhi portal or ULB/city authority.",
        "application_url": "https://pmsvanidhi.mohua.gov.in/",
        "official_source_url": "https://pmsvanidhi.mohua.gov.in/",
        "keywords": ["street vendor", "hawker", "micro credit", "urban"],
        "rules": [
            {"field": "occupation", "operator": "in", "value": ["self_employed", "business"], "description": "Street vendor/trader"},
            {"field": "age", "operator": "gte", "value": 18, "description": "Minimum age 18"},
        ],
        "documents": [{"title": "PM SVANidhi Overview", "content": "Working capital term loan for street vendors. Valid vending certificate required.", "source_url": "https://pmsvanidhi.mohua.gov.in/"}],
    },
    {
        "id": "SCH_PM_VISHWAKARMA",
        "name": "PM Vishwakarma Scheme",
        "short_description": "Support for traditional artisans and craftspeople with skill training and toolkit incentive.",
        "full_description": (
            "PM Vishwakarma provides recognition, skill upgradation, toolkit incentive of ₹15,000, "
            "and collateral-free credit up to ₹3 lakh for traditional artisans and craftspeople."
        ),
        "government_level": GovernmentLevel.CENTRAL,
        "ministry": "Ministry of Micro, Small & Medium Enterprises",
        "category": "Skill Development",
        "applicable_states": ["All India"],
        "benefits": ["₹15,000 toolkit incentive", "Skill training", "Collateral-free credit up to ₹3 lakh", "PM Vishwakarma certificate"],
        "required_documents": ["Aadhaar", "Bank account", "Artisan/craft proof"],
        "application_process": "Register on PM Vishwakarma portal with trade/category selection.",
        "application_url": "https://pmvishwakarma.gov.in/",
        "official_source_url": "https://pmvishwakarma.gov.in/",
        "keywords": ["artisan", "craftsman", "vishwakarma", "traditional"],
        "rules": [
            {"field": "occupation", "operator": "in", "value": ["self_employed", "business"], "description": "Traditional artisan/craftsperson"},
            {"field": "age", "operator": "gte", "value": 18, "description": "Minimum age 18"},
        ],
        "documents": [{"title": "PM Vishwakarma Trades", "content": "Covers 18 trades including carpenter, blacksmith, potter, tailor, barber, and more.", "source_url": "https://pmvishwakarma.gov.in/"}],
    },
    {
        "id": "SCH_APY",
        "name": "Atal Pension Yojana (APY)",
        "short_description": "Guaranteed minimum pension scheme for unorganized sector workers aged 18-40.",
        "full_description": "APY provides guaranteed minimum pension of ₹1,000-5,000/month after age 60 for subscribers in the unorganized sector.",
        "government_level": GovernmentLevel.CENTRAL,
        "ministry": "Ministry of Finance",
        "category": "Pension",
        "applicable_states": ["All India"],
        "benefits": ["Guaranteed pension ₹1,000-5,000/month", "Government co-contribution for eligible subscribers", "Spouse pension on subscriber death"],
        "required_documents": ["Aadhaar", "Bank account", "Mobile number"],
        "application_process": "Enroll through bank/post office with APY form.",
        "application_url": "https://npscra.nsdl.co.in/apy",
        "official_source_url": "https://www.india.gov.in/atal-pension-yojana",
        "keywords": ["pension", "retirement", "unorganized worker"],
        "rules": [
            {"field": "age", "operator": "gte", "value": 18, "description": "Minimum age 18"},
            {"field": "age", "operator": "lte", "value": 40, "description": "Maximum age 40"},
        ],
        "documents": [{"title": "APY Pension Slabs", "content": "Contribution varies by age and chosen pension amount. Tax benefits under Section 80CCD.", "source_url": "https://npscra.nsdl.co.in/apy"}],
    },
    {
        "id": "SCH_PMFBY",
        "name": "PM Fasal Bima Yojana (PMFBY)",
        "short_description": "Crop insurance scheme protecting farmers against crop loss due to natural calamities.",
        "full_description": "PMFBY provides comprehensive crop insurance at low premium rates for food crops, oilseeds, and commercial crops.",
        "government_level": GovernmentLevel.CENTRAL,
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "Agriculture",
        "applicable_states": ["All India"],
        "benefits": ["Low premium rates", "Coverage for crop loss", "Quick claim settlement", "Covers all stages of crop cycle"],
        "required_documents": ["Aadhaar", "Land records", "Bank account", "Sowing certificate"],
        "application_process": "Enroll through bank, CSC, or PMFBY portal during crop season.",
        "application_url": "https://pmfby.gov.in/",
        "official_source_url": "https://pmfby.gov.in/",
        "keywords": ["crop insurance", "farmer", "agriculture", "fasal"],
        "rules": [
            {"field": "occupation", "operator": "eq", "value": "farmer", "description": "Must be a farmer"},
            {"field": "has_land", "operator": "eq", "value": True, "description": "Must cultivate crops", "is_required": False},
        ],
        "documents": [{"title": "PMFBY Coverage", "content": "Premium: 2% for Kharif, 1.5% for Rabi, 5% for commercial crops. Covers yield loss and prevented sowing.", "source_url": "https://pmfby.gov.in/"}],
    },
    {
        "id": "SCH_KCC",
        "name": "Kisan Credit Card (KCC)",
        "short_description": "Flexible credit for farmers to meet agricultural and allied activity needs.",
        "full_description": "KCC provides timely and adequate credit to farmers for crop production, post-harvest expenses, and farm maintenance at subsidized interest rates.",
        "government_level": GovernmentLevel.CENTRAL,
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "Agriculture",
        "applicable_states": ["All India"],
        "benefits": ["Credit limit based on land holding", "Interest subvention at 7%", "Flexible repayment after harvest", "Covers crop and allied activities"],
        "required_documents": ["Aadhaar", "Land records", "Bank account", "Passport photo"],
        "application_process": "Apply at any commercial bank, cooperative bank, or RRB branch.",
        "application_url": "https://www.india.gov.in/kisan-credit-card-kcc-scheme",
        "official_source_url": "https://www.india.gov.in/kisan-credit-card-kcc-scheme",
        "keywords": ["farmer", "credit", "kisan", "agriculture loan"],
        "rules": [
            {"field": "occupation", "operator": "eq", "value": "farmer", "description": "Must be a farmer"},
        ],
        "documents": [{"title": "KCC Limits", "content": "Credit limit based on crops grown and scale of finance. Valid for 5 years with annual review.", "source_url": "https://www.india.gov.in/kisan-credit-card-kcc-scheme"}],
    },
    {
        "id": "SCH_UJJWALA",
        "name": "Pradhan Mantri Ujjwala Yojana 2.0",
        "short_description": "Free LPG connection for eligible women from BPL households.",
        "full_description": "PMUY provides free LPG connections to women from poor households to reduce indoor air pollution and health hazards from traditional cooking fuels.",
        "government_level": GovernmentLevel.CENTRAL,
        "ministry": "Ministry of Petroleum & Natural Gas",
        "category": "Women Welfare",
        "applicable_states": ["All India"],
        "benefits": ["Free LPG connection", "First refill and hotplate subsidy", "EMI facility for stove and refill"],
        "required_documents": ["Aadhaar", "BPL ration card or SECC reference", "Bank account"],
        "application_process": "Apply through LPG distributor or Ujjwala portal.",
        "application_url": "https://www.pmuy.gov.in/",
        "official_source_url": "https://www.pmuy.gov.in/",
        "keywords": ["lpg", "women", "bpl", "cooking gas"],
        "rules": [
            {"field": "is_woman", "operator": "eq", "value": True, "description": "Adult woman of household", "is_required": False},
            {"field": "gender", "operator": "eq", "value": "female", "description": "Female beneficiary", "is_required": False},
            {"field": "is_bpl", "operator": "eq", "value": True, "description": "BPL household", "is_required": False},
        ],
        "documents": [{"title": "PMUY Eligibility", "content": "Adult woman from BPL household without existing LPG connection. Extended to poor households without BPL card under 2.0.", "source_url": "https://www.pmuy.gov.in/"}],
    },
    {
        "id": "SCH_PMSBY",
        "name": "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
        "short_description": "Accident insurance cover of ₹2 lakh at ₹20/year premium.",
        "full_description": "PMSBY offers accidental death and disability insurance cover of ₹2 lakh for a nominal annual premium of ₹20, auto-debited from bank account.",
        "government_level": GovernmentLevel.CENTRAL,
        "ministry": "Ministry of Finance",
        "category": "Insurance",
        "applicable_states": ["All India"],
        "benefits": ["₹2 lakh accidental death/disability cover", "Premium only ₹20/year", "Auto-renewal via bank account"],
        "required_documents": ["Aadhaar", "Bank account with auto-debit consent"],
        "application_process": "Enroll through participating bank branch or net banking.",
        "application_url": "https://www.jansuraksha.gov.in/",
        "official_source_url": "https://www.jansuraksha.gov.in/Forms-PMSBY.aspx",
        "keywords": ["insurance", "accident", "suraksha bima"],
        "rules": [
            {"field": "age", "operator": "gte", "value": 18, "description": "Minimum age 18"},
            {"field": "age", "operator": "lte", "value": 70, "description": "Maximum age 70"},
        ],
        "documents": [{"title": "PMSBY Details", "content": "₹20 annual premium. Covers accidental death and total/permanent disability. Age 18-70 years.", "source_url": "https://www.jansuraksha.gov.in/"}],
    },
    {
        "id": "SCH_PMJJBY",
        "name": "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)",
        "short_description": "Life insurance cover of ₹2 lakh at ₹436/year premium.",
        "full_description": "PMJJBY provides life insurance cover of ₹2 lakh for death due to any reason at an annual premium of ₹436.",
        "government_level": GovernmentLevel.CENTRAL,
        "ministry": "Ministry of Finance",
        "category": "Insurance",
        "applicable_states": ["All India"],
        "benefits": ["₹2 lakh life cover", "Premium ₹436/year", "Covers death from any cause"],
        "required_documents": ["Aadhaar", "Bank account with auto-debit consent"],
        "application_process": "Enroll through participating bank branch.",
        "application_url": "https://www.jansuraksha.gov.in/",
        "official_source_url": "https://www.jansuraksha.gov.in/Forms-PMJJBY.aspx",
        "keywords": ["life insurance", "jeevan jyoti", "bima"],
        "rules": [
            {"field": "age", "operator": "gte", "value": 18, "description": "Minimum age 18"},
            {"field": "age", "operator": "lte", "value": 50, "description": "Maximum age 50 at entry"},
        ],
        "documents": [{"title": "PMJJBY Details", "content": "Renewable up to age 55. Premium auto-debited annually from linked bank account.", "source_url": "https://www.jansuraksha.gov.in/"}],
    },
    {
        "id": "SCH_ESHRAM",
        "name": "e-Shram Portal (Unorganized Worker Registration)",
        "short_description": "Free registration for unorganized workers with accident insurance and social security benefits.",
        "full_description": "e-Shram is a national database of unorganized workers providing a Universal Account Number (UAN) and access to social security schemes including accident insurance.",
        "government_level": GovernmentLevel.CENTRAL,
        "ministry": "Ministry of Labour & Employment",
        "category": "Social Security",
        "applicable_states": ["All India"],
        "benefits": ["Free accident insurance ₹2 lakh", "UAN for portability of benefits", "Access to welfare schemes", "Pension and skill training linkage"],
        "required_documents": ["Aadhaar", "Bank account", "Mobile number"],
        "application_process": "Self-register on e-Shram portal or through CSC.",
        "application_url": "https://register.eshram.gov.in/",
        "official_source_url": "https://eshram.gov.in/",
        "keywords": ["unorganized worker", "labour", "eshram", "gig worker"],
        "rules": [
            {"field": "age", "operator": "gte", "value": 16, "description": "Minimum age 16"},
            {"field": "age", "operator": "lte", "value": 59, "description": "Maximum age 59"},
            {"field": "occupation", "operator": "in", "value": ["laborer", "self_employed", "farmer", "homemaker"], "description": "Unorganized sector worker", "is_required": False},
        ],
        "documents": [{"title": "e-Shram Benefits", "content": "Covers construction workers, gig workers, domestic workers, street vendors, and other unorganized workers. Free PMSBY coverage on registration.", "source_url": "https://eshram.gov.in/"}],
    },
    {
        "id": "SCH_STARTUP_SEED",
        "name": "Startup India Seed Fund Scheme (SISFS)",
        "short_description": "Financial assistance to startups for proof of concept, prototype development, and market entry.",
        "full_description": "SISFS provides seed funding up to ₹20 lakh as grant and up to ₹50 lakh as debt/convertible debentures to DPIIT-recognized startups through incubators.",
        "government_level": GovernmentLevel.CENTRAL,
        "ministry": "Department for Promotion of Industry and Internal Trade",
        "category": "Entrepreneurship",
        "applicable_states": ["All India"],
        "benefits": ["Grant up to ₹20 lakh", "Investment up to ₹50 lakh", "Incubator support", "Mentorship access"],
        "required_documents": ["DPIIT startup recognition", "Business plan", "Pitch deck", "Incorporation certificate"],
        "application_process": "Apply through empanelled incubators on Startup India portal.",
        "application_url": "https://www.startupindia.gov.in/",
        "official_source_url": "https://www.startupindia.gov.in/content/sih/en/startup-schemes.html",
        "keywords": ["startup", "seed fund", "entrepreneur", "innovation"],
        "rules": [
            {"field": "age", "operator": "gte", "value": 18, "description": "Founder minimum age 18"},
            {"field": "occupation", "operator": "in", "value": ["self_employed", "business"], "description": "Startup founder"},
        ],
        "documents": [{"title": "SISFS Eligibility", "content": "DPIIT recognized startup less than 2 years old. Not received more than ₹10 lakh under other government schemes.", "source_url": "https://www.startupindia.gov.in/"}],
    },
    {
        "id": "SCH_NAPS",
        "name": "National Apprenticeship Promotion Scheme (NAPS)",
        "short_description": "Apprenticeship training with stipend support for youth in industry settings.",
        "full_description": "NAPS promotes apprenticeship training by sharing 25% of stipend (up to ₹1,500/month) paid by employers to apprentices in designated trades.",
        "government_level": GovernmentLevel.CENTRAL,
        "ministry": "Ministry of Skill Development & Entrepreneurship",
        "category": "Employment",
        "applicable_states": ["All India"],
        "benefits": ["On-the-job training", "Stipend during apprenticeship", "Industry-recognized certification", "Employment pathway"],
        "required_documents": ["Aadhaar", "Educational certificates", "Bank account"],
        "application_process": "Register on apprenticeship portal and apply to employer establishments.",
        "application_url": "https://www.apprenticeshipindia.gov.in/",
        "official_source_url": "https://www.apprenticeshipindia.gov.in/",
        "keywords": ["apprenticeship", "youth", "training", "employment"],
        "rules": [
            {"field": "age", "operator": "gte", "value": 14, "description": "Minimum age 14"},
            {"field": "age", "operator": "lte", "value": 35, "description": "Maximum age 35"},
            {"field": "education", "operator": "in", "value": ["class_10", "class_12", "graduate", "iti", "diploma"], "description": "Minimum education for trade"},
        ],
        "documents": [{"title": "NAPS Stipend", "content": "Government shares 25% of monthly stipend subject to ₹1,500 cap. Duration 6-36 months depending on trade.", "source_url": "https://www.apprenticeshipindia.gov.in/"}],
    },
    {
        "id": "SCH_NRLM",
        "name": "Deendayal Antyodaya Yojana - NRLM (Aajeevika)",
        "short_description": "Self-employment and skill training for rural poor women through SHGs.",
        "full_description": "DAY-NRLM organizes rural poor women into Self Help Groups (SHGs) and provides microfinance, skill training, and livelihood support.",
        "government_level": GovernmentLevel.CENTRAL,
        "ministry": "Ministry of Rural Development",
        "category": "Rural Development",
        "applicable_states": ["All India"],
        "benefits": ["SHG formation support", "Revolved fund and community investment fund", "Skill training", "Market linkage"],
        "required_documents": ["Aadhaar", "Bank account", "SHG membership"],
        "application_process": "Contact Block/District Rural Livelihood Mission office for SHG formation.",
        "application_url": "https://aajeevika.gov.in/",
        "official_source_url": "https://aajeevika.gov.in/",
        "keywords": ["shg", "rural women", "livelihood", "aajeevika"],
        "rules": [
            {"field": "is_woman", "operator": "eq", "value": True, "description": "Women SHG members", "is_required": False},
            {"field": "gender", "operator": "eq", "value": "female", "description": "Rural women", "is_required": False},
            {"field": "is_bpl", "operator": "eq", "value": True, "description": "BPL/poor household", "is_required": False},
        ],
        "documents": [{"title": "NRLM SHG Model", "content": "Targets rural poor households. SHGs receive bank linkage, interest subvention, and capacity building support.", "source_url": "https://aajeevika.gov.in/"}],
    },
    {
        "id": "SCH_KA_YUVA_NIDHI",
        "name": "Karnataka Yuva Nidhi Scheme",
        "short_description": "Unemployment allowance for graduate youth in Karnataka.",
        "full_description": "Karnataka Yuva Nidhi provides monthly unemployment allowance to graduates and diploma holders who are unemployed and Karnataka domiciles.",
        "government_level": GovernmentLevel.STATE,
        "ministry": "Department of Skill Development, Karnataka",
        "category": "Employment",
        "applicable_states": ["Karnataka"],
        "benefits": ["Monthly unemployment allowance", "Graduate: ₹3,000/month", "Diploma holder: ₹1,500/month for up to 2 years"],
        "required_documents": ["Karnataka domicile", "Graduation/diploma certificate", "Aadhaar", "Unemployment declaration"],
        "application_process": "Apply on Seva Sindhu portal during application window.",
        "application_url": "https://sevasindhu.karnataka.gov.in/",
        "official_source_url": "https://sevasindhu.karnataka.gov.in/",
        "keywords": ["karnataka", "unemployment", "graduate", "youth"],
        "rules": [
            {"field": "state", "operator": "eq", "value": "karnataka", "description": "Karnataka domicile"},
            {"field": "occupation", "operator": "eq", "value": "unemployed", "description": "Must be unemployed"},
            {"field": "education", "operator": "in", "value": ["graduate", "diploma"], "description": "Graduate or diploma holder"},
            {"field": "age", "operator": "gte", "value": 18, "description": "Minimum age 18"},
            {"field": "age", "operator": "lte", "value": 35, "description": "Maximum age 35"},
        ],
        "documents": [{"title": "Yuva Nidhi Details", "content": "For graduates passing out in 2023-24. Not availing other similar allowance. Family income criteria apply.", "source_url": "https://sevasindhu.karnataka.gov.in/"}],
    },
    {
        "id": "SCH_MH_LADKI_BAHIN",
        "name": "Mukhyamantri Majhi Ladki Bahin Yojana (Maharashtra)",
        "short_description": "Monthly financial assistance of ₹1,500 to eligible women in Maharashtra.",
        "full_description": "Maharashtra government scheme providing ₹1,500/month to women aged 21-65 from eligible families meeting income criteria.",
        "government_level": GovernmentLevel.STATE,
        "ministry": "Women & Child Development, Maharashtra",
        "category": "Women Welfare",
        "applicable_states": ["Maharashtra"],
        "benefits": ["₹1,500/month direct transfer", "Covers eligible women 21-65 years", "DBT to bank account"],
        "required_documents": ["Aadhaar", "Domicile/residence proof", "Income certificate", "Bank account", "Ration card"],
        "application_process": "Apply through Nari Shakti Doot app or setu.maharashtra.gov.in.",
        "application_url": "https://ladkibahin.maharashtra.gov.in/",
        "official_source_url": "https://ladkibahin.maharashtra.gov.in/",
        "keywords": ["maharashtra", "women", "financial assistance"],
        "rules": [
            {"field": "state", "operator": "eq", "value": "maharashtra", "description": "Maharashtra resident"},
            {"field": "gender", "operator": "eq", "value": "female", "description": "Women beneficiary"},
            {"field": "is_woman", "operator": "eq", "value": True, "description": "Female applicant"},
            {"field": "age", "operator": "gte", "value": 21, "description": "Minimum age 21"},
            {"field": "age", "operator": "lte", "value": 65, "description": "Maximum age 65"},
            {"field": "annual_family_income", "operator": "lte", "value": 250000, "description": "Family income up to ₹2.5 lakh"},
        ],
        "documents": [{"title": "Ladki Bahin Eligibility", "content": "Annual family income up to ₹2.5 lakh. Excludes income tax payers and certain government employees.", "source_url": "https://ladkibahin.maharashtra.gov.in/"}],
    },
    {
        "id": "SCH_UP_KANYA_SUMANGALA",
        "name": "Mukhyamantri Kanya Sumangala Yojana (UP)",
        "short_description": "Financial assistance for girl child education and marriage in Uttar Pradesh.",
        "full_description": "UP Kanya Sumangala provides tiered financial support at birth, vaccination, Class 1, Class 6, Class 9, graduation, and marriage milestones for girl children.",
        "government_level": GovernmentLevel.STATE,
        "ministry": "Women & Child Development, Uttar Pradesh",
        "category": "Women Welfare",
        "applicable_states": ["Uttar Pradesh"],
        "benefits": ["Total up to ₹15,000 in installments", "Supports education milestones", "Direct bank transfer"],
        "required_documents": ["Aadhaar", "Birth certificate", "UP domicile", "Bank account", "Income certificate"],
        "application_process": "Register on MKSY portal with girl child details.",
        "application_url": "https://mksy.up.gov.in/",
        "official_source_url": "https://mksy.up.gov.in/",
        "keywords": ["uttar pradesh", "girl child", "education", "kanya"],
        "rules": [
            {"field": "state", "operator": "eq", "value": "uttar pradesh", "description": "UP domicile"},
            {"field": "gender", "operator": "eq", "value": "female", "description": "Girl child beneficiary"},
            {"field": "annual_family_income", "operator": "lte", "value": 300000, "description": "Family income up to ₹3 lakh", "is_required": False},
        ],
        "documents": [{"title": "MKSY Installments", "content": "Installments at birth (₹2,000), vaccination, Class 1, 6, 9, graduation, and marriage milestones.", "source_url": "https://mksy.up.gov.in/"}],
    },
    {
        "id": "SCH_BIHAR_SCC",
        "name": "Bihar Student Credit Card Scheme",
        "short_description": "Education loan up to ₹4 lakh at 4% interest for higher education in Bihar.",
        "full_description": "Bihar SCC provides collateral-free education loans up to ₹4 lakh at 4% simple interest for students pursuing professional/technical courses after Class 12.",
        "government_level": GovernmentLevel.STATE,
        "ministry": "Education Department, Bihar",
        "category": "Education",
        "applicable_states": ["Bihar"],
        "benefits": ["Loan up to ₹4 lakh", "4% simple interest", "Covers tuition, hostel, books", "Moratorium during course"],
        "required_documents": ["Aadhaar", "Class 12 mark sheet", "Admission letter", "Bihar domicile", "Income certificate", "Bank account"],
        "application_process": "Apply on 7nishchay-yuvaupmission.bihar.gov.in portal.",
        "application_url": "https://7nishchay-yuvaupmission.bihar.gov.in/",
        "official_source_url": "https://7nishchay-yuvaupmission.bihar.gov.in/",
        "keywords": ["bihar", "education loan", "student", "credit card"],
        "rules": [
            {"field": "state", "operator": "eq", "value": "bihar", "description": "Bihar domicile"},
            {"field": "education", "operator": "in", "value": ["class_12", "graduate", "diploma"], "description": "Pursuing higher education"},
            {"field": "occupation", "operator": "eq", "value": "student", "description": "Student", "is_required": False},
            {"field": "age", "operator": "lte", "value": 25, "description": "Maximum age 25", "is_required": False},
        ],
        "documents": [{"title": "Bihar SCC Details", "content": "For technical/professional courses in recognized institutions. State government provides interest subsidy.", "source_url": "https://7nishchay-yuvaupmission.bihar.gov.in/"}],
    },
    {
        "id": "SCH_RJ_PALANHAR",
        "name": "Rajasthan Palanhar Yojana",
        "short_description": "Monthly grant for guardians raising orphan/vulnerable children in Rajasthan.",
        "full_description": "Palanhar Yojana provides monthly financial assistance to foster families/guardians caring for orphan, abandoned, or vulnerable children in Rajasthan.",
        "government_level": GovernmentLevel.STATE,
        "ministry": "Social Justice & Empowerment, Rajasthan",
        "category": "Child Welfare",
        "applicable_states": ["Rajasthan"],
        "benefits": ["₹1,000-2,500/month per child", "Additional education grant", "Covers up to 3 children per guardian"],
        "required_documents": ["Guardian Aadhaar", "Child birth certificate", "Death certificate of parents (if applicable)", "Bank account", "Residence proof"],
        "application_process": "Apply at e-Mitra kiosk or Social Justice Department office.",
        "application_url": "https://palanhaar.rajasthan.gov.in/",
        "official_source_url": "https://palanhaar.rajasthan.gov.in/",
        "keywords": ["rajasthan", "orphan", "child welfare", "palanhar"],
        "rules": [
            {"field": "state", "operator": "eq", "value": "rajasthan", "description": "Rajasthan resident"},
        ],
        "documents": [{"title": "Palanhar Grant Slabs", "content": "Higher grant for SC/ST/BPL children. Guardian must not be receiving similar benefit from other scheme.", "source_url": "https://palanhaar.rajasthan.gov.in/"}],
    },
    {
        "id": "SCH_TN_FREE_BUS",
        "name": "Tamil Nadu Free Bus Travel for Women",
        "short_description": "Free bus travel for women in ordinary fare government buses across Tamil Nadu.",
        "full_description": "Tamil Nadu provides free travel for women in ordinary fare city/town buses operated by state transport corporations, boosting mobility and economic participation.",
        "government_level": GovernmentLevel.STATE,
        "ministry": "Transport Department, Tamil Nadu",
        "category": "Women Welfare",
        "applicable_states": ["Tamil Nadu"],
        "benefits": ["Free travel in ordinary fare buses", "Zero ticket in city/town services", "Covers all TNSTC buses"],
        "required_documents": ["Identity proof (Aadhaar/voter ID)", "Tamil Nadu residence"],
        "application_process": "No registration required. Show identity proof to conductor when boarding.",
        "application_url": "https://www.tn.gov.in/",
        "official_source_url": "https://www.tn.gov.in/scheme/free-bus-travel-women",
        "keywords": ["tamil nadu", "women", "free bus", "transport"],
        "rules": [
            {"field": "state", "operator": "eq", "value": "tamil nadu", "description": "Tamil Nadu resident"},
            {"field": "gender", "operator": "eq", "value": "female", "description": "Women passengers"},
            {"field": "is_woman", "operator": "eq", "value": True, "description": "Female beneficiary"},
        ],
        "documents": [{"title": "Free Bus Scheme", "content": "Applicable on ordinary fare services only. Express and deluxe services excluded.", "source_url": "https://www.tn.gov.in/"}],
    },
    {
        "id": "SCH_NMMS",
        "name": "National Means-cum-Merit Scholarship (NMMS)",
        "short_description": "Scholarship of ₹12,000/year for meritorious Class 8 students from economically weaker sections.",
        "full_description": "NMMS provides ₹1,000/month scholarship to selected Class 8 students from economically weaker sections to continue secondary education.",
        "government_level": GovernmentLevel.CENTRAL,
        "ministry": "Ministry of Education",
        "category": "Education",
        "applicable_states": ["All India"],
        "benefits": ["₹12,000/year scholarship", "Supports Classes 9-12", "Merit-based selection exam"],
        "required_documents": ["Class 7 mark sheet", "Income certificate", "Aadhaar", "School enrollment proof"],
        "application_process": "Appear for NMMS state-level exam conducted by SCERT.",
        "application_url": "https://scholarships.gov.in/",
        "official_source_url": "https://scholarships.gov.in/",
        "keywords": ["scholarship", "student", "class 8", "merit"],
        "rules": [
            {"field": "occupation", "operator": "eq", "value": "student", "description": "Student", "is_required": False},
            {"field": "education", "operator": "in", "value": ["class_10", "class_12"], "description": "Continuing secondary education"},
            {"field": "annual_family_income", "operator": "lte", "value": 350000, "description": "Family income up to ₹3.5 lakh"},
        ],
        "documents": [{"title": "NMMS Exam", "content": "Selection via MAT and SAT exams in Class 8. 1 lakh scholarships awarded annually across states.", "source_url": "https://scholarships.gov.in/"}],
    },
    {
        "id": "SCH_POST_MATRIC_SC",
        "name": "Post Matric Scholarship for SC Students",
        "short_description": "Central scholarship covering tuition and maintenance for SC students in post-matriculation courses.",
        "full_description": "Post Matric Scholarship for SC students provides reimbursement of compulsory non-refundable fees and maintenance allowance for pursuing post-secondary education.",
        "government_level": GovernmentLevel.CENTRAL,
        "ministry": "Ministry of Social Justice & Empowerment",
        "category": "Education",
        "applicable_states": ["All India"],
        "benefits": ["Full tuition reimbursement", "Maintenance allowance", "Study tour charges", "Thesis typing/printing charges"],
        "required_documents": ["Caste certificate (SC)", "Income certificate", "Aadhaar", "Previous mark sheets", "Admission proof", "Bank account"],
        "application_process": "Apply on National Scholarship Portal during application period.",
        "application_url": "https://scholarships.gov.in/",
        "official_source_url": "https://scholarships.gov.in/",
        "keywords": ["sc scholarship", "post matric", "education", "caste"],
        "rules": [
            {"field": "caste_category", "operator": "eq", "value": "sc", "description": "SC category student"},
            {"field": "occupation", "operator": "eq", "value": "student", "description": "Student", "is_required": False},
            {"field": "education", "operator": "in", "value": ["class_12", "graduate", "post_graduate", "diploma"], "description": "Post-matric course"},
            {"field": "annual_family_income", "operator": "lte", "value": 250000, "description": "Parental income up to ₹2.5 lakh"},
        ],
        "documents": [{"title": "Post Matric SC Scholarship", "content": "Income ceiling ₹2.5 lakh. Covers all recognized post-matriculation courses including professional degrees.", "source_url": "https://scholarships.gov.in/"}],
    },
    {
        "id": "SCH_PUNJAB_SMART",
        "name": "Punjab Smart Ration Card Scheme",
        "short_description": "Subsidized food grains and additional benefits for eligible families in Punjab.",
        "full_description": "Punjab Smart Ration Card provides subsidized wheat, dal, and sugar to eligible BPL and AAY families through digitized PDS.",
        "government_level": GovernmentLevel.STATE,
        "ministry": "Food & Civil Supplies, Punjab",
        "category": "Food Security",
        "applicable_states": ["Punjab"],
        "benefits": ["Subsidized food grains", "Digital ration card", "Portability within state", "Additional welfare linkage"],
        "required_documents": ["Aadhaar", "Residence proof", "Income certificate", "Family photo"],
        "application_process": "Apply at food supply office or Punjab government portal.",
        "application_url": "https://punjab.gov.in/",
        "official_source_url": "https://punjab.gov.in/smart-ration-card",
        "keywords": ["punjab", "ration", "food security", "bpl"],
        "rules": [
            {"field": "state", "operator": "eq", "value": "punjab", "description": "Punjab resident"},
            {"field": "is_bpl", "operator": "eq", "value": True, "description": "BPL/AAY family", "is_required": False},
            {"field": "annual_family_income", "operator": "lte", "value": 200000, "description": "Low income household", "is_required": False},
        ],
        "documents": [{"title": "Smart Ration Card", "content": "Digitized PDS for transparent food grain distribution. Linked with Aadhaar for biometric authentication.", "source_url": "https://punjab.gov.in/"}],
    },
]
